version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school
    ports:
      - "3306:3306"

  app:
    image: student  # Replace with your image
    container_name: springboot-student-app
    depends_on:
      - mysql
    ports:
      - "3737:3737"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/school
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: on-failure
